ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER samjo IDENTIFIED BY samjo default TABLESPACE USERS;
GRANT CONNECT, RESOURCE, CREATE JOB, CREATE VIEW, CREATE ANY CONTEXT TO samjo;
ALTER USER samjo QUOTA UNLIMITED ON USERS;

